### ISSUE TITLE
removing lz4 and lua socket

### ISSUE THREAD

**Issue by CDSoft** [CDSoft/luax#6]
I'm thinking about removing lz4 and lua socket:

- lz4 can be replaced with lzip (compression level 0). It provides a better compression ratio and remains rather fast.
- lua socket integration in LuaX is not complete, SSL support is missing and would require more dependencies. Moreover lua socket can easily be installed with luarocks.

Does somebody have any strong reasons to keep these modules in LuaX?

**Comment by KernelKinetic** [comment]
Hello Christoph and thanks for the great work with luax! I like it very much because I can use it standalone and portable for most of the tasks without using any additional tools. Using luarocks portable is a pain. I would vote not only for keeping luasocket but also for adding  SSL since I just need it for some projects. I would even help in development and would try to write some code for SSL integration if appreciated.

**Comment by CDSoft** [comment]
SSL support can be added to luasocket with luasec but it requires openssl.
I made it kind of work on Linux, compile on macos but not on Windows yet.
I think I will make OpenSSL optional to be able to build two flavours of luax (reduced or complete with luasec and openssl).

**Comment by CDSoft** [comment]
It seems to also works for windows (tested on Linux with wine...).

So I've added an option to compile luax with luasec and openssl. This patch is on master (version 7.3)

**Comment by KernelKinetic** [comment]
Good idea and great news, thanks for implementing this way! I just tried on macos aarm64 and it fails with the following message compiling because I didn't clone the repository with `--recurse-submodules`. Maybe you should add such a hint to the documentation.

`/bin/sh: .../luax/ext/opt/openssl/Configure: No such file or directory
FAILED: .build/openssl/linux-x86_64/libssl.a .build/openssl/linux-x86_64/libcrypto.a`

I'll try on windows tomorrow and will tell you here.

**Comment by CDSoft** [comment]
I have updated the documentation.

**Comment by KernelKinetic** [comment]
Nice, thank you. I've tried to compile it on windows using wsl, but it's running out of memory during the compilation of openssl. Should I try mingw? What is your intended way to compile luax on windows?

**Comment by CDSoft** [comment]
I guess wsl is just Linux. Compiling natively on Windows is in fact not supported. In theory it should work with zig but their should be some dependencies I've not though of (supporting compilation on windows is not on my plans).

The compilation of openssl uses lots of memory since `make -j` may compile all sources in parallel. I should maybe limit the number of parallel process (e.g. replace "-j" by "-j8" in build.lua, line 267).

When I test LuaX on Windows, I mean just executing LuaX, not necessarily compiling it.

**Comment by KernelKinetic** [comment]
It works on windows for me, so from my point of view this issue can be closed. Thank you for this solution!

**Comment by CDSoft** [comment]
Thanks for your tests.
